// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: queryServer.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	QueryDevicesServe_QueryDevices_FullMethodName = "/QueryDevicesServe/QueryDevices"
)

// QueryDevicesServeClient is the client API for QueryDevicesServe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryDevicesServeClient interface {
	QueryDevices(ctx context.Context, in *QueryDevicesRequest, opts ...grpc.CallOption) (*QueryDevicesResponse, error)
}

type queryDevicesServeClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryDevicesServeClient(cc grpc.ClientConnInterface) QueryDevicesServeClient {
	return &queryDevicesServeClient{cc}
}

func (c *queryDevicesServeClient) QueryDevices(ctx context.Context, in *QueryDevicesRequest, opts ...grpc.CallOption) (*QueryDevicesResponse, error) {
	out := new(QueryDevicesResponse)
	err := c.cc.Invoke(ctx, QueryDevicesServe_QueryDevices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryDevicesServeServer is the server API for QueryDevicesServe service.
// All implementations must embed UnimplementedQueryDevicesServeServer
// for forward compatibility
type QueryDevicesServeServer interface {
	QueryDevices(context.Context, *QueryDevicesRequest) (*QueryDevicesResponse, error)
}

// UnimplementedQueryDevicesServeServer must be embedded to have forward compatible implementations.
type UnimplementedQueryDevicesServeServer struct {
}

func (UnimplementedQueryDevicesServeServer) QueryDevices(context.Context, *QueryDevicesRequest) (*QueryDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDevices not implemented")
}

// UnsafeQueryDevicesServeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryDevicesServeServer will
// result in compilation errors.
type UnsafeQueryDevicesServeServer interface {
	mustEmbedUnimplementedQueryDevicesServeServer()
}

func RegisterQueryDevicesServeServer(s grpc.ServiceRegistrar, srv QueryDevicesServeServer) {
	s.RegisterService(&QueryDevicesServe_ServiceDesc, srv)
}

func _QueryDevicesServe_QueryDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryDevicesServeServer).QueryDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryDevicesServe_QueryDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryDevicesServeServer).QueryDevices(ctx, req.(*QueryDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QueryDevicesServe_ServiceDesc is the grpc.ServiceDesc for QueryDevicesServe service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueryDevicesServe_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "QueryDevicesServe",
	HandlerType: (*QueryDevicesServeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryDevices",
			Handler:    _QueryDevicesServe_QueryDevices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "queryServer.proto",
}
